### ISSUE TITLE
kore-config.js

### ISSUE THREAD

**Issue by vit100** [Koredotcom/web-kore-sdk#10]
file with config is here: `UI/kore-config.js` 
This file has `clientSecret` prop.

Is this secret value should be secret or it is not secret? Point is that anyone can "borrow" this info.

**Comment by SrinivasaraoYa-Kore** [comment]
Hi @vit100 This SDK is a reference implementation and useful to give quick demos your management or clients with no code changes. As a best practice JWT token will be generated at the backend. So while integrating SDK code in the website,  Client Id & Secret will be maintained at backend to generate JWT token and never exposed in the SDK code.
