### ISSUE TITLE
Multiple instances of the bot share context

### ISSUE THREAD

**Issue by vit100** [Koredotcom/web-kore-sdk#11]
What is correct usage of the bot in situation when it integrated with web application with only one bot configuration (Configuration is set of clientId, secret, bot id, etc - from kore-config.js).

This host app with embedded bot is used by different users.

Problem is that all chat of one user is visible on instance of another user, on different computer.

**Comment by SrinivasaraoYa-Kore** [comment]
@vit100 please use our community portal (community.kore.ai) for your queries.
