### ISSUE TITLE
Architecture Question

### ISSUE THREAD

**Issue by teadsPfizer** [Koredotcom/web-kore-sdk#18]
I see a lot of jquery .html or plan javascript setInnerHTML,is this safe to use if i copy this exisiting pattern for custom templates with no inputs? Also do you have any plans on converting this into a TypeScript codebase or creating type definitions for the chatWindow.js and kore-client-sdk.js? It would be really helpful to gain intellisense ide support as well as type safety for times when we need to create custom addons.

**Comment by VenkateswararaoVe-Kore** [comment]
kore-web-sdk supports TypeScript.
